### ISSUE TITLE
Error trying to :UnrealGenWithEngine  (Win11)

### ISSUE THREAD

**Issue by MilosLord** [zadirion/Unreal.nvim#3]
Upon configuring the plugin and doing :UnrealGenWithEngine, I get Error in update:...te\pack\packer\start\Unreal.nvim/lua/unreal/commands.lua:887: ...te\pack\packer\start\Unreal.nvim/lua/unreal/commands.lua:326: bad argument #1 to 'lines' (\: No such file or directory)

The engine path is properly set up and ended in UnrealNvim.json, and I'm using the command inside my source file (MyPawn). I properly installed it with packer, and there are no errors
 "EngineDir": "D:\\UE_5.3\\"
 
 compile commands.json generated:
 [
	{
		"file": "C:\\Users\\kobas\\Documents\\Unreal Projects\\MyProject2\\Source\\MyProject2\\MyCharacter.cpp",
		"command": "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe\" @\"C:\\Users\\kobas\\Documents\\Unreal Projects\\MyProject2\\Intermediate\\Build\\Win64\\x64\\UnrealEditor\\Development\\MyProject2\\MyCharacter.cpp.obj.rsp.gcd\"",
		"directory": "D:\\UE_5.3\\Engine\\Source"
	},
	{
		"file": "C:\\Users\\kobas\\Documents\\Unreal Projects\\MyProject2\\Source\\MyProject2\\MyProject2.cpp",
		"command": "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe\" @\"C:\\Users\\kobas\\Documents\\Unreal Projects\\MyProject2\\Intermediate\\Build\\Win64\\x64\\UnrealEditor\\Development\\MyProject2\\MyProject2.cpp.obj.rsp.gcd\"",
		"directory": "D:\\UE_5.3\\Engine\\Source"
	}
]

**Comment by zadirion** [comment]
the backslashes in the engine path need to be \\ instead of \
can you try that please and let me know if it works for you?
